/**
 * Created by brettwatanabe on 1/6/16.
 */

var patientData =
    [
    {
        "DOI": "11-15-2015",
        "R/L": "L",
        "RAJL": 43.5,
        "RFR": 147,
        "RER": 0,
        "LASTNAME": "BOB",
        "COM DATE": "02-29-2016",
        "id": 2,
        "LSF": 4,
        "LSE": 4,
        "LAJL": 40.5,
        "ADJUSTOR": "Woof",
        "EMPLOYER": "Some Company",
        "PAIN": 5,
        "LFR": 130,
        "PHYSICIAN": "Ferdinand Bardamu",
        "A/D": "A",
        "LJL": 36,
        "RBJL": 37,
        "START": "12-18-2015",
        "DIAGNOSIS": "Left Knee Pain",
        "LBJL": 35,
        "FIRSTNAME": "BILLY",
        "RSE": 5,
        "RSF": 5,
        "LER": 0,
        "RJL": 36.5,
        "INSURANCE": "Feel Good"
    },
    {
        "DOI": "07-04-2012",
        "R/L": "R",
        "RAJL": 40.5,
        "RFR": 148,
        "RER": 0,
        "LASTNAME": "SHMO",
        "COM DATE": "02-29-2016",
        "id": 3,
        "LSF": 5,
        "LSE": 5,
        "LAJL": 41,
        "ADJUSTOR": "Meow",
        "EMPLOYER": null,
        "PAIN": 5,
        "LFR": 150,
        "PHYSICIAN": "Yuri Zhivago",
        "A/D": "A",
        "LJL": 33,
        "RBJL": 32,
        "START": "12-18-2015",
        "DIAGNOSIS": "Right Knee Arthritis",
        "LBJL": 31.5,
        "FIRSTNAME": "JOE",
        "RSE": 4,
        "RSF": 4,
        "LER": 0,
        "RJL": 33,
        "INSURANCE": "Just Dance"
    },
    {
        "DOI": "12-11-2015",
        "R/L": "R",
        "RAJL": 46.5,
        "RFR": 90,
        "RER": 5,
        "LASTNAME": "YAMADA",
        "COM DATE": "03-31-2016",
        "id": 4,
        "LSF": 5,
        "LSE": 5,
        "LAJL": 48,
        "ADJUSTOR": null,
        "EMPLOYER": "Relax",
        "PAIN": 6,
        "LFR": 135,
        "PHYSICIAN": "T.J. Eckleburg",
        "A/D": "A",
        "LJL": 37.5,
        "RBJL": 38,
        "START": "12-18-2015",
        "DIAGNOSIS": "Pain in Right Knee; s/p Microfracture",
        "LBJL": 37.5,
        "FIRSTNAME": "YUKI",
        "RSE": 3,
        "RSF": 3,
        "LER": 0,
        "RJL": 38.5,
        "INSURANCE": "Rest Insured"
    },
    {
        "DOI": "11-15-2015",
        "R/L": "B",
        "RAJL": 53,
        "RFR": 138,
        "RER": 0,
        "LASTNAME": "OROZCO",
        "COM DATE": "02-29-2016",
        "id": 5,
        "LSF": 4,
        "LSE": 4,
        "LAJL": 50.5,
        "ADJUSTOR": null,
        "EMPLOYER": null,
        "PAIN": null,
        "LFR": 136,
        "PHYSICIAN": "Sarah Cooper",
        "A/D": "A",
        "LJL": 38,
        "RBJL": 40,
        "START": "12-19-2015",
        "DIAGNOSIS": "Bilateral Knee OA",
        "LBJL": 38.5,
        "FIRSTNAME": "MARISA",
        "RSE": 4,
        "RSF": 4,
        "LER": 0,
        "RJL": 38,
        "INSURANCE": null
    },
    {
        "DOI": "12-08-2015",
        "R/L": "L",
        "RAJL": 46,
        "RFR": 135,
        "RER": 0,
        "LASTNAME": "DONAUDI",
        "COM DATE": "01-31-2016",
        "id": 6,
        "LSF": 4,
        "LSE": 4,
        "LAJL": 44.5,
        "ADJUSTOR": null,
        "EMPLOYER": null,
        "PAIN": 5,
        "LFR": 120,
        "PHYSICIAN": "Susan Wheeler",
        "A/D": "D",
        "LJL": 36.5,
        "RBJL": 36.5,
        "START": "12-11-2015",
        "DIAGNOSIS": "Left Knee Osteochondral Defect",
        "LBJL": 36,
        "FIRSTNAME": "STEPHANO",
        "RSE": 5,
        "RSF": 5,
        "LER": 5,
        "RJL": 35.5,
        "INSURANCE": null
    }
];

console.log("patientData", patientData);

var app = angular.module('app',[]);
app.controller('PatientsCtrl', ['$scope',function($scope) {
    $scope.patientData = patientData;
    $scope.selectedPatient = $scope.patientData[0];
}]);